# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

glmPR <- function(x_, y_, lambda_, rho_) {
    .Call('glmPR_glmPR', PACKAGE = 'glmPR', x_, y_, lambda_, rho_)
}

